# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PAcBMocvi91i5s2sdq5tEhY5GUJNIrO8
"""

from google.colab import files
uploaded=files.upload()
print(uploaded)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import glob

print(glob.glob("/content/*"))

import pandas as pd
import glob

files = glob.glob("/content/*.csv")

print("CSV files found:")
print(files)

hospital_file = [f for f in files if "Hospital" in f][0]

df = pd.read_csv(hospital_file)

print("✅ Dataset loaded successfully!")
print("Shape:", df.shape)

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nColumn Names:")
print(df.columns.tolist())

df.head

print("Missing values in each column:")
print(df.isnull().sum())

missing_percent = (df.isnull().sum() / len(df)) * 100
print(missing_percent)

print("Number of duplicate rows:", df.duplicated().sum())

df=df.drop_duplicates()

print("Duplicates after removal:", df.duplicated().sum())

df.columns = df.columns.str.strip()
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ", "_")

print(df.columns.tolist())

for i, col in enumerate(df.columns, 1):
    print(i, col)

for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].str.strip()

df.describe()

print([col for col in df.columns if "gender" in col or "sex" in col])

print(df['gender'].value_counts())

import matplotlib.pyplot as plt

df['gender'].value_counts().plot(kind='bar')

plt.title("Male vs Female Patients")
plt.xlabel("Gender")
plt.ylabel("Number of Patients")
plt.show()

print(df.columns.tolist())

print("Final dataset shape:", df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

missing_percent = (df.isnull().sum() / len(df)) * 100

print(missing_percent)

threshold = 2

missing_percent = (df.isnull().sum() / len(df)) * 100

columns_to_remove = missing_percent[missing_percent > threshold].index

df = df.drop(columns=columns_to_remove)

print("Removed columns:")
print(columns_to_remove.tolist())

import pandas as pd
import glob

files = glob.glob("/content/Hospital Patient*.csv")

print("Files found:")
print(files)

df = pd.read_csv(files[0])

print("Dataset loaded successfully!")
print("Rows and Columns:", df.shape)

df.head()

from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

print("Missing Values in Each Column:")
print(df.isnull().sum())

print("Number of Duplicate Rows:")
print(df.duplicated().sum())

df = df.drop_duplicates()

print("Rows and Columns After Removing Duplicates:")
print(df.shape)

print("Duplicates Remaining:", df.duplicated().sum())

print("Dataset Information:")
df.info()

df.to_csv("hospital_cleaned_amrutha.csv", index=False)
print("Cleaned dataset saved!")