# -*- coding: utf-8 -*-
"""Infosys Internship

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VuhNNJRYlYcLNfkeIczzpCWEz056Fk7h
"""

import pandas as pd
import numpy as np
from google.colab import files

uploaded = files.upload()

df = pd.read_csv("healthcare_dataset_dirty-1.csv")

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.info()

display(df.describe(include="all"))

"""Data Cleaning"""

missing_count = df.isnull().sum() #Checking Missing Values
display(missing_count[missing_count > 0])

missing_percentage = (df.isnull().sum() / len(df)) * 100 # Check missing-value percentage
display(missing_percentage[missing_percentage > 0])

# Total missing values in entire dataset
total_missing = df.isnull().sum().sum()
# Total cells in entire dataset
total_cells = df.shape[0] * df.shape[1]
# Overall missing value percentage
overall_missing_percentage = (total_missing / total_cells) * 100
print("Total Missing Values:", total_missing)
print("Total Cells:", total_cells)
print("Overall Missing Value Percentage:",
      round(overall_missing_percentage, 4), "%") #Show total missing values

# Check invalid negative billing amounts
negative_billing = df[df["Billing Amount"] < 0]

print("Negative billing records:", len(negative_billing))

display(
    negative_billing[
        ["Name", "Billing Amount"]
    ].head(20)
)

df = df[df["Billing Amount"] >= 0].copy()

print(
    "Negative billing amounts after cleaning:",
    (df["Billing Amount"] < 0).sum()
)

numeric_columns = df.select_dtypes(include=np.number).columns # Numeric Columns

for col in numeric_columns:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].median())

text_columns = df.select_dtypes(include="object").columns # Text Columns

for col in text_columns:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].mode()[0])

print("Total missing values after cleaning:", df.isnull().sum().sum()) # After cleaning

duplicate_count = df.duplicated().sum() #Check duplicate records
print("Duplicate records found:", duplicate_count)

if duplicate_count > 0: # Duplicate Records
    display(df[df.duplicated(keep=False)])
else:
    print("No duplicate records found.")

if duplicate_count > 0: # Removing Duplicates
    df = df.drop_duplicates()
    print("Duplicate records removed.")
else:
    print("No duplicates to remove.")

print("Duplicate records after cleaning:", df.duplicated().sum()) # Verifying Duplicates

df = df.copy()
text_columns = df.select_dtypes(include="object").columns # Check leading/trailing spaces
for col in text_columns:
    space_rows = df[df[col].notna() & (df[col] != df[col].str.strip())]
    if len(space_rows) > 0:
        print(f"\nColumn: {col}")
        print("Rows containing leading/trailing spaces:", len(space_rows))
        display(space_rows[[col]].head())

for col in text_columns: # Removing Spaces
    df[col] = df[col].str.strip()

remaining_spaces = 0 # Verifying spaces
for col in text_columns:
    remaining_spaces += (
        df[col].notna() & (df[col] != df[col].str.strip())
    ).sum()
print("Remaining leading/trailing spaces:", remaining_spaces)

# Check inconsistent capitalization in all text columns

text_columns = df.select_dtypes(include="object").columns

for col in text_columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts().head(20))

# Standardize capitalization
for col in text_columns:
    df[col] = df[col].str.strip()
    # General text standardization
    if col != "Blood Type":
        df[col] = df[col].str.title()
# Blood Type needs uppercase format
if "Blood Type" in df.columns:
    df["Blood Type"] = df["Blood Type"].str.upper()
# Insurance Provider correction
if "Insurance Provider" in df.columns:
    df["Insurance Provider"] = (
        df["Insurance Provider"]
        .str.lower()
        .replace({
            "cigna": "Cigna",
            "medicare": "Medicare",
            "unitedhealthcare": "UnitedHealthcare",
            "blue cross": "Blue Cross",
            "aetna": "Aetna"
        })
    )

print("Standardization applied successfully.")

for col in text_columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts().head(20))

"""Transformations

"""

print(df.dtypes)# checking data types

df["Date of Admission"] = pd.to_datetime(
    df["Date of Admission"],
    errors="coerce"
)

df["Discharge Date"] = pd.to_datetime(
    df["Discharge Date"],
    errors="coerce"
)

df["Age"] = pd.to_numeric(
    df["Age"],
    errors="coerce"
).astype("Int64")

print("Data Types After Correction:") #After Transformation
display(df.dtypes)

df["Billing Amount"] = df["Billing Amount"].round(2) # Billing amount rounded to 2 decimals
display(df[["Billing Amount"]].head())

df["First Name"] = df["Name"].str.split().str[0] # Splitting First and last names
df["Last Name"] = df["Name"].str.split().str[-1]
display(
    df[["Name", "First Name", "Last Name"]].head()
)

df["Length of Stay"] = (
    df["Discharge Date"] - df["Date of Admission"]
).dt.days

display(            # Creating length of stay
    df[
        [
            "Date of Admission",
            "Discharge Date",
            "Length of Stay"
        ]
    ].head()
)

# Dividing the age Group
df["Age Group"] = pd.cut(
    df["Age"],
    bins=[0, 12, 18, 35, 60, 120],
    labels=[
        "Child",
        "Teenager",
        "Young Adult",
        "Adult",
        "Senior"
    ],
    include_lowest=True
)
display(
    df[["Age", "Age Group"]].head(10)
)

# Creating Billing Category
df["Billing Category"] = pd.cut(
    df["Billing Amount"],
    bins=[0, 10000, 25000, 50000, float("inf")],
    labels=[
        "Low",
        "Medium",
        "High",
        "Very High"
    ]
)
display(
    df[
        ["Billing Amount", "Billing Category"]
    ].head(10)
)

# Extracting month and year
df["Admission Month"] = df["Date of Admission"].dt.month_name()
df["Admission Year"] = df["Date of Admission"].dt.year
display(
    df[
        ["Date of Admission", "Admission Month", "Admission Year"]
    ].head(10)
)

# staying category based on how many days they stayed
df["Stay Category"] = pd.cut(
    df["Length of Stay"],
    bins=[-1, 7, 14, 30, float("inf")],
    labels=[
        "Short Stay",
        "Medium Stay",
        "Long Stay",
        "Very Long Stay"
    ]
)
display(
    df[
        ["Length of Stay", "Stay Category"]
    ].head(10)
)

print("Total Patients:",
      len(df))
print("Total Billing Amount:",
      round(df["Billing Amount"].sum(), 2))
print("Average Billing Amount:",
      round(df["Billing Amount"].mean(), 2))
print("Average Length of Stay:",
      round(df["Length of Stay"].mean(), 2),
      "days")
print("Total Doctors:",
      df["Doctor"].nunique())
print("Total Hospitals:",
      df["Hospital"].nunique())

if "Patient Count" in df.columns:
    df.drop(columns=["Patient Count"], inplace=True)

print("Patient Count column removed.")

# Check final dataset
print("Final dataset shape:", df.shape)
# Save the cleaned and transformed dataset
file_name = "hospital_cleaned_transformed_dataset.csv"
df.to_csv(file_name, index=False)
print("Dataset saved successfully as:", file_name)

from google.colab import files

files.download("hospital_cleaned_transformed_dataset.csv")