# -*- coding: utf-8 -*-
"""Info_Internship

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XKazxJY1uKTCY-PJthXJMc4OE5jCD29d
"""

import pandas as pd
from google.colab import files

# Upload all required CSV files
uploaded = files.upload()

patients = pd.read_csv("patient.csv")
admissions = pd.read_csv("admission.csv")
departments = pd.read_csv("department.csv")
wards = pd.read_csv("ward.csv")
beds = pd.read_csv("bed.csv")
billing = pd.read_csv("billing.csv")
staff_assignment = pd.read_csv("staff_assignment.csv")
employee = pd.read_csv("employee.csv")
patient_insurance = pd.read_csv("insurance_provider.csv")
disease = pd.read_csv("disease.csv")
patient_diagnostic = pd.read_csv("diagnostic_test.csv")

tables = {
    "Patients": patients,
    "Admissions": admissions,
    "Departments": departments,
    "Wards": wards,
    "Beds": beds,
    "Billing": billing,
    "Staff Assignment": staff_assignment,
    "Employee": employee,
    "Disease": disease,
}

for name, df in tables.items():
    print(name)
    print("Rows:", len(df))
    print("Columns:", df.columns.tolist())

raw_master = admissions.copy()
raw_master = raw_master.merge(
    patients,
    on="patient_id",
    how="left"
)
raw_master = raw_master.merge(
    departments,
    on="department_id",
    how="left",
    suffixes=("", "_department")
)
raw_master = raw_master.merge(
    wards,
    on="ward_id",
    how="left",
    suffixes=("", "_ward")
)
raw_master = raw_master.merge(
    beds,
    on="bed_id",
    how="left",
    suffixes=("", "_bed")
)
raw_master = raw_master.merge(
    disease,
    on="disease_id",
    how="left",
    suffixes=("", "_disease")
)
billing_summary = (
    billing
    .groupby("admission_id")
    .agg(
        Total_Billing=("total_amount", "sum"),
        Insurance_Covered_Amount=(
            "insurance_covered_amount",
            "sum"
        ),
        Patient_Payable_Amount=(
            "patient_payable_amount",
            "sum"
        )
    )
    .reset_index()
)

raw_master = raw_master.merge(
    billing_summary,
    on="admission_id",
    how="left"
)

staff_summary = (
    staff_assignment
    .groupby("ward_id")
    .agg(
        Staff_Count=(
            "employee_id",
            "nunique"
        ),
        Staff_Assignment_Count=(
            "assignment_id",
            "nunique"
        )
    )
    .reset_index()
)

raw_master = raw_master.merge(
    staff_summary,
    on="ward_id",
    how="left"
)


employee_summary = (
    employee
    .groupby("department_id")
    .agg(
        Employee_Count=(
            "employee_id",
            "nunique"
        )
    )
    .reset_index()
)

raw_master = raw_master.merge(
    employee_summary,
    on="department_id",
    how="left"
)

print("RAW DATA INTEGRATION COMPLETED")
print("Total Rows:", len(raw_master))
print(
    "Total Columns:",
    len(raw_master.columns)
)

file_name = "hospital_raw_integrated.xlsx"

raw_master.to_excel(
    file_name,
    index=False
)

print(
    "\n✅ File saved successfully:",
    file_name
)
files.download(file_name)

"""Cleaning DataSet

"""

import pandas as pd
import numpy as np
df = pd.read_excel("/content/hospital_dirty_dataset(Infosys).xlsx")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
display(df.head())

# Check complete duplicate records

duplicate_count = df.duplicated().sum()

print("Duplicate records BEFORE cleaning:", duplicate_count)

if duplicate_count > 0:
    display(
        df[df.duplicated(keep=False)].head(20)
    )
else:
    print("No duplicate records found.")

if duplicate_count > 0:
    df = df.drop_duplicates().copy()
    print("Duplicate records removed.")
else:
    print("No duplicates to remove.")

remaining_duplicates = df.duplicated().sum()

print(
    "Duplicate records AFTER cleaning:",
    remaining_duplicates
)

if remaining_duplicates == 0:
    print(" Duplicate cleaning completed successfully.")

#Column-wise missing values
missing_count = df.isnull().sum()

print(" MISSING VALUES BEFORE CLEANING")

display(
    missing_count[missing_count > 0]
)

missing_percentage = (
    df.isnull().sum() / len(df)
) * 100

print("===== MISSING PERCENTAGE BEFORE CLEANING =====")

display(
    missing_percentage[missing_percentage > 0]
)

# Overall missing percentage
total_missing = df.isnull().sum().sum()
total_cells = df.shape[0] * df.shape[1]

overall_missing_percentage = (
    total_missing / total_cells
) * 100

print("Total Missing Values:", total_missing)
print("Total Cells:", total_cells)
print(
    "Overall Missing Percentage:",
    round(overall_missing_percentage, 2),
    "%"
)

# Handling
numeric_columns = df.select_dtypes(
    include=np.number
).columns

text_columns = df.select_dtypes(
    include="object"
).columns
# Numeric columns → median
for col in numeric_columns:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(
            df[col].median()
        )
# Text columns → mode
for col in text_columns:
    if df[col].isnull().sum() > 0:
        mode_value = df[col].mode()

        if len(mode_value) > 0:
            df[col] = df[col].fillna(
                mode_value[0]
            )

remaining_missing = df.isnull().sum().sum()
print(
    "Total missing values AFTER cleaning:",
    remaining_missing
)

if remaining_missing == 0:
    print(" Missing-value cleaning completed successfully.")
else:
    print(" Missing values still remain.")

    display(
        df.isnull().sum()[
            df.isnull().sum() > 0
        ]
    )

# Check spaces BEFORE standardization
print("SPACE CHECK BEFORE CLEANING")
space_count = 0
for col in text_columns:
    count = (
        df[col].notna()
        & (df[col] != df[col].str.strip())
    ).sum()
    if count > 0:
        print(
            col,
            ":",
            count,
            "records with leading/trailing spaces"
        )

        space_count += count

print(
    "\nTotal records containing spaces:",
    space_count
)

# Removing
for col in text_columns:
    df[col] = df[col].str.strip()

remaining_spaces = 0
for col in text_columns:
    remaining_spaces += (
        df[col].notna()
        & (df[col] != df[col].str.strip())
    ).sum()

print(
    "Remaining leading/trailing spaces:",
    remaining_spaces
)

if remaining_spaces == 0:
    print("Space cleaning completed.")

# Standardize Department Names
print("DEPARTMENT NAMES BEFORE STANDARDIZATION")

display(
    df["department_name"]
    .value_counts()
)

df["department_name"] = (
    df["department_name"]
    .astype(str)
    .str.strip()
    .str.title()
)

print("DEPARTMENT NAMES AFTER STANDARDIZATION")
display(
    df["department_name"]
    .value_counts()
)

# Data Types
print("DATA TYPES BEFORE CORRECTION")

display(df.dtypes)

# changing data types
date_columns = [
    "admission_date",
    "discharge_date",
    "date_of_birth"
]

for col in date_columns:
    if col in df.columns:
        df[col] = pd.to_datetime(
            df[col],
            errors="coerce"
        )
numeric_cols = [
    "floor_number",
    "total_beds",
    "Total_Billing",
    "Insurance_Covered_Amount",
    "Patient_Payable_Amount",
    "Staff_Count",
    "Staff_Assignment_Count",
    "Employee_Count"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

print("DATA TYPES AFTER CORRECTION")
display(df.dtypes)

if "blood_group" in df.columns:
    df["blood_group"] = (
        df["blood_group"]
        .astype(str)
        .str.strip()
        .str.upper()
    )

# Extracting month and year
df["Admission_Month"] = (
    df["admission_date"]
    .dt.month_name()
)
df["Admission_Year"] = (
    df["admission_date"]
    .dt.year
)

# Normalizing Billing Vlaues
billing_columns = [
    "Total_Billing",
    "Insurance_Covered_Amount",
    "Patient_Payable_Amount"
]
for col in billing_columns:
    if col in df.columns:
        df[col] = pd.to_numeric(
            df[col],
            errors="coerce"
        )
        df[col] = df[col].round(2)

# Checking negative values
for col in billing_columns:
    if col in df.columns:
        print(
            col,
            "negative values:",
            (df[col] < 0).sum()
        )

df["date_of_birth"] = pd.to_datetime(
    df["date_of_birth"],
    errors="coerce"
)
# Calculate Age
today = pd.Timestamp.today()

df["Age"] = (
    today.year - df["date_of_birth"].dt.year
    - (
        (today.month < df["date_of_birth"].dt.month)
        |
        (
            (today.month == df["date_of_birth"].dt.month)
            &
            (today.day < df["date_of_birth"].dt.day)
        )
    )
)

# Convert to nullable integer
df["Age"] = df["Age"].astype("Int64")

# Display calculated Age
display(
    df[
        ["date_of_birth", "Age"]
    ].head(10)
)

# Dividing the age Group
df["Age Group"] = pd.cut(
    df["Age"],
    bins=[0, 12, 18, 35, 60, 120],
    labels=[
        "Child",
        "Teenager",
        "Young Adult",
        "Adult",
        "Senior"
    ],
    include_lowest=True
)
display(
    df[["Age", "Age Group"]].head(10)
)

# Creating Billing Category
df["Billing Category"] = pd.cut(
    df["Total_Billing"],
    bins=[0, 10000, 25000, 50000, float("inf")],
    labels=[
        "Low",
        "Medium",
        "High",
        "Very High"
    ],
    include_lowest=True
)

display(
    df[
        ["Total_Billing", "Billing Category"]
    ].head(10)
)

print("Total Patients:",
      df["patient_id"].nunique())
print("Total Admissions:",
      df["admission_id"].nunique())
print("Total Billing Amount:",
      round(df["Total_Billing"].sum(), 2))
print("Average Billing Amount:",
      round(df["Total_Billing"].mean(), 2))
print("Total Departments:",
      df["department_id"].nunique())
print("Total Wards:",
      df["ward_id"].nunique())
print("Total Beds:",
      df["bed_id"].nunique())
print("Total Diseases:",
      df["disease_id"].nunique())

# Check final dataset
print("Final dataset shape:", df.shape)
# Save the cleaned and transformed dataset
file_name = "hospital_cleaned_transformed_dataset.csv"
df.to_csv(file_name, index=False)
print("Dataset saved successfully as:", file_name)

from google.colab import files

files.download("hospital_cleaned_transformed_dataset.csv")





